# ============================================================
# service.py — app/modules/symptom_checker/service.py
# ============================================================
import json
import logging

from app.core.config import settings
from app.core.llm_client import client
from app.shared.rag import medical_search
from app.shared.specialties import ALLOWED_SPECIALTIES
from app.shared.topic_lock import (
    TOPIC_MISMATCH_MESSAGES,
    is_topic_mismatch,
    resolve_language,
)

from .constants import EMERGENCY_KEYWORDS, SEARCH_QUERY_SUFFIX
from .prompts import build_system_prompt

logger = logging.getLogger(__name__)


def _contains_emergency_keyword(message: str) -> bool:
    lowered = message.lower()
    return any(keyword in lowered for keyword in EMERGENCY_KEYWORDS)


def ask_ai(
    message: str,
    history: list[dict] | None = None,
    locked_specialty: str | None = None,
) -> dict:
    """
    Calls the AI to analyze symptoms. Returns a dict with:
      - reply: message shown in chat (in the user's detected language),
        with a "Nguồn tham khảo" footer appended when sources were used
      - suggestedSpecialties: list of specialty codes
      - sources: list of reference sources actually used (attached by our
        code, never invented by the AI)
      - emergency: True if an emergency pattern was detected (hard keyword check)
      - topicMismatch: True if the question belongs to a different specialty
        than the one already locked for this conversation (see
        app.shared.topic_lock.is_topic_mismatch). When True, `reply` is our
        own fixed refusal text (NOT generated by the LLM), and
        suggestedSpecialties/sources are left empty.
    """
    is_emergency = _contains_emergency_keyword(message)
    context_chunks = medical_search.retrieve(message, extra_query_terms=SEARCH_QUERY_SUFFIX)
    sources = [{"title": c["title"], "url": c["url"]} for c in context_chunks]

    messages = [{"role": "system", "content": build_system_prompt(context_chunks)}]
    if history:
        messages.extend(history)
    messages.append({"role": "user", "content": message})

    try:
        response = client.chat.completions.create(
            model=settings.MODEL_NAME,
            messages=messages,
            temperature=0.3,  # low temperature keeps answers stable, less "creative" drift
            response_format={"type": "json_object"},
        )
        raw = response.choices[0].message.content
        parsed = json.loads(raw)

        specialties = [
            s for s in parsed.get("suggestedSpecialties", [])
            if s in ALLOWED_SPECIALTIES
        ]
        reply = parsed.get("reply", "Xin lỗi, tôi chưa thể trả lời câu hỏi này.")
        language = resolve_language(parsed.get("language"))

        # Emergency luôn được ưu tiên tuyệt đối — bỏ qua kiểm tra chủ đề.
        if is_emergency:
            reply = (
                "⚠️ Triệu chứng bạn mô tả có thể là dấu hiệu cấp cứu. Vui lòng gọi ngay "
                "115 hoặc đến cơ sở y tế gần nhất để được xử lý kịp thời.\n\n" + reply
            )
            if "EMERGENCY" not in specialties:
                specialties.insert(0, "EMERGENCY")
            reply += medical_search.format_sources_footer(sources)
            return {
                "reply": reply,
                "suggestedSpecialties": specialties,
                "sources": sources,
                "emergency": True,
                "topicMismatch": False,
            }

        if is_topic_mismatch(locked_specialty, specialties):
            return {
                "reply": TOPIC_MISMATCH_MESSAGES[language],
                "suggestedSpecialties": [],
                "sources": [],
                "emergency": False,
                "topicMismatch": True,
            }

        reply += medical_search.format_sources_footer(sources)

        return {
            "reply": reply,
            "suggestedSpecialties": specialties,
            "sources": sources,
            "emergency": False,
            "topicMismatch": False,
        }

    except json.JSONDecodeError:
        logger.warning("AI returned invalid JSON")
        return {
            "reply": "Xin lỗi, tôi gặp sự cố khi xử lý câu trả lời. Bạn vui lòng thử lại nhé.",
            "suggestedSpecialties": ["EMERGENCY"] if is_emergency else [],
            "sources": sources,
            "emergency": is_emergency,
            "topicMismatch": False,
        }
    except Exception as ex:
        logger.error("Error calling AI: %s", ex)
        return {
            "reply": "Xin lỗi, hệ thống đang gặp sự cố. Bạn vui lòng thử lại sau ít phút.",
            "suggestedSpecialties": ["EMERGENCY"] if is_emergency else [],
            "sources": sources,
            "emergency": is_emergency,
            "topicMismatch": False,
        }